# Generated by Django 5.0 on 2024-01-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grafica',
            fields=[
                ('id_gpu', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad_gb', models.SmallIntegerField()),
                ('tipo_gddr', models.CharField(max_length=20)),
                ('pci', models.SmallIntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('ruta_imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('gama', models.CharField(max_length=20)),
                ('enlace_pagina', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id_ram', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad_gb', models.SmallIntegerField()),
                ('tipo_ddr', models.CharField(max_length=20)),
                ('velocidad_mhz', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('ruta_imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('gama', models.CharField(max_length=20)),
                ('enlace_pagina', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id_cpu', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ruta_imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('enlace_pagina', models.CharField(blank=True, max_length=200, null=True)),
                ('socket', models.CharField(max_length=20)),
                ('velocidad_ghz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nucleos', models.IntegerField(blank=True, null=True)),
                ('hilos', models.IntegerField(blank=True, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('gama', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usu', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaMadre',
            fields=[
                ('id_mom', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('socket', models.CharField(max_length=50)),
                ('tipo_memoria', models.CharField(max_length=50)),
                ('cant_ranuras_memoria', models.IntegerField()),
                ('max_memoria', models.IntegerField()),
                ('formato', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ruta_imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('gama', models.CharField(max_length=20)),
                ('pci', models.SmallIntegerField()),
                ('grafica_uso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piecomputador.grafica')),
                ('procesador_uso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piecomputador.procesador')),
                ('ram_uso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piecomputador.memoria')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id_armado', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_armado', models.CharField(max_length=100)),
                ('id_memoria_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piecomputador.memoria')),
                ('id_tarjeta_grafica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piecomputador.grafica')),
                ('id_procesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piecomputador.procesador')),
                ('id_tarjeta_madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piecomputador.tarjetamadre')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_armado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piecomputador.pc')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piecomputador.usuarios')),
            ],
            options={
                'unique_together': {('id_usu', 'id_armado')},
            },
        ),
    ]
